# Introdução ao `numpy`
Escrever texto incial aqui...

In [7]:
import numpy as np
import matplotlib.pyplot as plt  # Biblioteca para gerar gráficos

Vamos criar umas matrizes e vetores para começar...

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\ &
\boldsymbol{B} &= \begin{bmatrix}1 & 3\\ 5 & 7\end{bmatrix}\\\\
\boldsymbol{v}_1 &= \begin{bmatrix}5 & 3\end{bmatrix}\ &
\boldsymbol{v}_2 &= \begin{bmatrix}9 & 2 & 1\end{bmatrix}
\end{aligned}$$

In [5]:
A = np.array([[2,0],[4,6],[8,2]])
B = np.array([[1,3],[5,7]])
v1 = np.array([5,3])
v2 = np.array([9,2,1])

In [20]:
print('Dimensão do A: ',A.shape)
print('Dimensão do B: ',B.shape)
print('Dimensão do v1: ',v1.shape)
print('Dimensão do v2: ',v2.shape)

Dimensão do A:  (3, 2)
Dimensão do B:  (2, 2)
Dimensão do v1:  (2,)
Dimensão do v2:  (3,)


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\boldsymbol{A}^{\mathbf{T}} &= \begin{bmatrix}2 & 4 & 8\\ 0 & 6 & 2\end{bmatrix}
\end{aligned}$$

In [7]:
print(A.T)

[[2 4 8]
 [0 6 2]]


$$\begin{aligned}
\mathtt{A[0]} &= \begin{bmatrix}2 & 0\end{bmatrix}\\
\mathtt{A[[0,2]]} &= \begin{bmatrix}2 & 0\\ 8 & 2\\ 2 & 0\end{bmatrix}\\
\end{aligned}$$

In [20]:
print(A[:,[0,1]])

[[2 0]
 [4 6]
 [8 2]]


In [22]:
print(A[0], A[0].shape) # Primeira linha de A
print(A[[0,2]], A[[0,2]].shape) # Primeira e terceira linha de A
print(A[[0]], A[[0]].shape) # Primeira linha de A

[2 0] (2,)
[[2 0]
 [8 2]] (2, 2)
[[2 0]] (1, 2)


$$\begin{aligned}
\mathtt{A[:,0]} &= \begin{bmatrix}2 & 4 & 8\end{bmatrix}\\
\mathtt{A[:,[0]]} &= \begin{bmatrix}2 \\ 4 \\ 8\end{bmatrix}
\end{aligned}$$

In [23]:
print(A[:,0], A[:,0].shape) # Primeira coluna do A
print(A[:,[0,1]], A[:,[0,1]].shape) # Primeira e segunda coluna do A
print(A[:,[0]], A[:,[0]].shape) # Primeira coluna do A

[2 4 8] (3,)
[[2 0]
 [4 6]
 [8 2]] (3, 2)
[[2]
 [4]
 [8]] (3, 1)


## Matrizes notáveis

$$\begin{aligned}
\boldsymbol{I}_n = \mathtt{np.eye(n)} &= \begin{bmatrix}1 & 0 & \ldots\\ 0 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 1\end{bmatrix}&
\boldsymbol{0}_{n,m} = \mathtt{np.zeros((n,m))} &= \begin{bmatrix}0 & 0 & \ldots\\ 0 & 0 & \ldots\\ \vdots&\vdots&\vdots\\ 0 & \ldots & 0\end{bmatrix}\\
\boldsymbol{1}_{n,m} = \mathtt{np.ones((n,m))} &= \begin{bmatrix}1 & 1 & \ldots\\ 1 & 1 & \ldots\\ \vdots&\vdots&\vdots\\ 1 & \ldots & 1\end{bmatrix}\\
\end{aligned}$$

In [24]:
print(np.eye(5))
print(np.zeros((5,3)))
print(np.ones((3,1)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]
 [1.]]


Além dessas matrizes notáveis, também podemos fazer matrizes aleatórias:

`np.random.rand(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.rand(n,m)}]_{ij} \sim \mathcal{U}(0,1)$.

Ou seja, $[\mathtt{np.random.rand(n,m)}]_{ij} \in [0,1)$

`np.random.randn(n,m)` é uma matrix $n$ por $m$ onde $[\mathtt{np.random.randn(n,m)}]_{ij} \sim \mathcal{N}(0,1)$

Ou seja, $[\mathtt{np.random.randn(n,m)}]_{ij} \in (-\infty,+\infty)$

In [41]:
print(np.random.rand(5,3))
#print(np.random.randn(2,2))

[[0.64521219 0.83193533 0.46178671]
 [0.44629706 0.55134814 0.83487007]
 [0.45606713 0.62455772 0.66758689]
 [0.31286532 0.30653453 0.24193345]
 [0.89226109 0.39394041 0.10339922]]


## Operações lineares

In [30]:
print(5 * A)

[[10  0]
 [20 30]
 [40 10]]


Ou seja...
$$\begin{aligned}
\mathtt{5 * A} = 5\boldsymbol{A} &= \begin{bmatrix}2\cdot 5 & 0\cdot 5\\ 4\cdot 5 & 6\cdot 5\\ 8\cdot 5 & 2\cdot 5\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}10 & 0\\ 20 & 30\\ 40 & 10\end{bmatrix}
\end{aligned}$$

In [31]:
print(A + A)

[[ 4  0]
 [ 8 12]
 [16  4]]


Ou seja...
$$\begin{aligned}
\mathtt{A + A} = \boldsymbol{A}+\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}4 & 0\\ 8 & 12\\ 26 & 4\end{bmatrix}
\end{aligned}$$

In [32]:
print(v1 * A)

[[10  0]
 [20 18]
 [40  6]]


$$\begin{aligned}
\mathtt{v1 * A} = \boldsymbol{v}_1 \odot \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\odot\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5\cdot 2 & 3\cdot 0\\ 5\cdot 4 & 3\cdot 6\\ 5\cdot 8 & 3\cdot 2\end{bmatrix}\\
&= \begin{bmatrix}10 & 0\\ 20 & 18\\ 40 & 6\end{bmatrix}\\
\end{aligned}$$

In [33]:
print(v1 + A)

[[ 7  3]
 [ 9  9]
 [13  5]]


$$\begin{aligned}
\mathtt{v1 + A} = \boldsymbol{v}_1 \oplus \boldsymbol{A} &= \begin{bmatrix}5 & 3\end{bmatrix}\oplus\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\[0.3em]
&= \begin{bmatrix}5 & 3\\ 5 & 3\\ 5 & 3\end{bmatrix}+\begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
&= \begin{bmatrix}7 & 3\\ 9 & 9\\ 13 & 5\end{bmatrix}\\
\end{aligned}$$

In [37]:
try:
    v2 + A
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,) (3,2) 


In [38]:
try:
    A + B
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,2) (2,2) 


## Operações não-lineares

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{A ** 2} &= \begin{bmatrix}2^2 & 0^2\\ 4^2 & 6^2\\ 8^2 & 2^2\end{bmatrix}
\end{aligned}$$

In [70]:
print(A ** 2)

[[ 4  0]
 [16 36]
 [64  4]]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.sqrt(A)} &= \begin{bmatrix}\sqrt{2} & \sqrt{0}\\ \sqrt{4} & \sqrt{6}\\ \sqrt{8} & \sqrt{2}\end{bmatrix}\\
\mathtt{A ** 0.5} &= \begin{bmatrix}2^\frac{1}{2} & 0^\frac{1}{2}\\ 4^\frac{1}{2} & 6^\frac{1}{2}\\ 8^\frac{1}{2} & 2^\frac{1}{2}\end{bmatrix}
\end{aligned}$$

In [39]:
print(np.sqrt(A))
print(A ** 0.5)

[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]
[[1.41421356 0.        ]
 [2.         2.44948974]
 [2.82842712 1.41421356]]


## Operações de agregação

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A)} &= \frac{2 + 0 + 4 + 6 + 8 + 2}{2\cdot 3}\\
\mathtt{np.sum(A)} &= 2 + 0 + 4 + 6 + 8 + 2\\
\mathtt{np.prod(A)} &= 2 \cdot 0 \cdot 4 \cdot 6 \cdot 8 \cdot 2\\
\end{aligned}$$

In [42]:
np.mean(A), np.sum(A), np.prod(A)

(3.6666666666666665, 22, 0)

$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=0)} &= \frac{1}{3}\begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=0)} &= \begin{bmatrix}2 + 4 + 8 & 0 + 6 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=0)} &= \begin{bmatrix}2 \cdot 4 \cdot 8 & 0 \cdot 6 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [53]:
#np.mean(A, axis=0), np.sum(A, axis=0), np.prod(A, axis=0)
print(np.sum(A, axis=0))

[14  8]


$$\begin{aligned}
\boldsymbol{A} &= \begin{bmatrix}2 & 0\\ 4 & 6\\ 8 & 2\end{bmatrix}\\
\mathtt{np.mean(A, axis=1)} &= \frac{1}{2}\begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.sum(A, axis=1)} &= \begin{bmatrix}2 + 0 & 4 + 6 & 8 + 2\end{bmatrix}\\
\mathtt{np.prod(A, axis=1)} &= \begin{bmatrix}2 \cdot 0 & 4 \cdot 6 & 8 \cdot 2\end{bmatrix}\\
\end{aligned}$$

In [36]:
np.mean(A, axis=1), np.sum(A, axis=1), np.prod(A, axis=1)

(array([1., 5., 5.]), array([ 2, 10, 10]), array([ 0, 24, 16]))

In [40]:
np.mean(A, axis=0, keepdims=True)

array([[4.66666667, 2.66666667]])

In [43]:
A - np.mean(A, axis=0, keepdims=True)

array([[-2.66666667, -2.66666667],
       [-0.66666667,  3.33333333],
       [ 3.33333333, -0.66666667]])

## Multiplicação de Matriz

Para matrizes $\boldsymbol{X} \in \mathbb{R}^{a\times b}$ e $\boldsymbol{Y} \in \mathbb{R}^{b\times c}$, temos que
$\boldsymbol{XY} \in \mathbb{R}^{a\times c}$. Em Python, essa operação é representada por $\texttt{X @ Y}$.

A multiplicação é definida por:
$$\begin{aligned}
(\boldsymbol{XY})_{ij} = \sum_k \boldsymbol{X}_{ik}\boldsymbol{Y}_{kj}
\end{aligned}$$

In [16]:
print(A @ B)
print('Dimensão de A @ B: ',(A@B).shape)

[[ 2  6]
 [34 54]
 [18 38]]
Dimensão de A @ B:  (3, 2)


In [17]:
try:
    B @ A
except Exception as e:
    print(e)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [18]:
print(A @ B @ v1)
print((A @ B) @ v1)

[ 28 332 204]
[ 28 332 204]


### Inversão de matriz
Outra operação bastante comum é multiplicar uma matriz pela inversa dela...

Seja $\boldsymbol{B}$ uma matriz inversível, então $\boldsymbol{B}^{-1} \boldsymbol{B} = \boldsymbol{I}$


In [19]:
print(B)

[[1 3]
 [5 7]]


In [20]:
B_inv = np.linalg.inv(B)
print(B_inv)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [21]:
print(B_inv @ B)

[[ 1.00000000e+00  4.44089210e-16]
 [-1.11022302e-16  1.00000000e+00]]


Também funciona com vetores:
$\boldsymbol{B}^{-1} \boldsymbol{v}_1$

In [22]:
print(B_inv @ v1)

[-3.25  2.75]


Porém, existe uma outra forma mais eficiente de computar a mesma coisa:

Se $\boldsymbol{B}^{-1} \boldsymbol{v}_1 = \boldsymbol{x}$, então $\boldsymbol{B} \boldsymbol{x} = \boldsymbol{v}_1$.
Ou seja, estamos resolvendo o sistema de equações lineares com coeficientes $\boldsymbol{B}$ e resultado $\boldsymbol{v}_1$

In [23]:
print(np.linalg.solve(B,v1))

[-3.25  2.75]


In [24]:
print(np.linalg.solve(B,B))

[[ 1.00000000e+00  0.00000000e+00]
 [-3.46944695e-17  1.00000000e+00]]


## Leitura de arquivos com dados

Normalmente os dados na disciplina serão recebidos no formato CSV, isso significa que o dado é estruturado da seguinte maneira:
```
idade, pressão_sanguínea # Um cabeçalho opcional
39, 144 # Dados separados por vírgulas ou outro separador
47, 220
....
```

In [25]:
pressão_dataset = np.genfromtxt('./pressão.txt', delimiter=',', skip_header=1)
pressão_dataset

array([[ 39., 144.],
       [ 47., 220.],
       [ 45., 138.],
       [ 47., 145.],
       [ 65., 162.],
       [ 46., 142.],
       [ 67., 170.],
       [ 42., 124.],
       [ 67., 158.],
       [ 56., 154.],
       [ 64., 162.],
       [ 56., 150.],
       [ 59., 140.],
       [ 34., 110.],
       [ 42., 128.],
       [ 48., 130.],
       [ 45., 135.],
       [ 17., 114.],
       [ 20., 116.],
       [ 19., 124.],
       [ 36., 136.],
       [ 50., 142.],
       [ 39., 120.],
       [ 21., 120.],
       [ 44., 160.],
       [ 53., 158.],
       [ 63., 144.],
       [ 29., 130.],
       [ 25., 125.],
       [ 69., 175.]])

In [26]:
peixe_dataset = np.genfromtxt('./peixe.txt', delimiter=',')
peixe_dataset

array([[  14.,   25.,  620.],
       [  28.,   25., 1315.],
       [  41.,   25., 2120.],
       [  55.,   25., 2600.],
       [  69.,   25., 3110.],
       [  83.,   25., 3535.],
       [  97.,   25., 3935.],
       [ 111.,   25., 4465.],
       [ 125.,   25., 4530.],
       [ 139.,   25., 4570.],
       [ 153.,   25., 4600.],
       [  14.,   27.,  625.],
       [  28.,   27., 1215.],
       [  41.,   27., 2110.],
       [  55.,   27., 2805.],
       [  69.,   27., 3255.],
       [  83.,   27., 4015.],
       [  97.,   27., 4315.],
       [ 111.,   27., 4495.],
       [ 125.,   27., 4535.],
       [ 139.,   27., 4600.],
       [ 153.,   27., 4600.],
       [  14.,   29.,  590.],
       [  28.,   29., 1305.],
       [  41.,   29., 2140.],
       [  55.,   29., 2890.],
       [  69.,   29., 3920.],
       [  83.,   29., 3920.],
       [  97.,   29., 4515.],
       [ 111.,   29., 4520.],
       [ 125.,   29., 4525.],
       [ 139.,   29., 4565.],
       [ 153.,   29., 4566.],
       [  

## Exercícios

### Computar a fórmula da normalização escore-Z

Dado um conjunto de dados $\boldsymbol{X} = [\boldsymbol{x}_0, \boldsymbol{x}_1, \ldots, \boldsymbol{x}_n]$, a normalização por escore-Z é dada por:
$$\boldsymbol{x_i} = \frac{\boldsymbol{x_i} - \boldsymbol{\mu}}{\boldsymbol{\sigma}}$$

Onde:
$$\begin{aligned}
\boldsymbol{\mu} &= \frac{1}{n}\sum_i^n \boldsymbol{x_i}\\
\boldsymbol{\sigma} &= \sqrt{\frac{1}{n-1}\sum_i^n (\boldsymbol{x_i}-\boldsymbol{\mu})^2}\\
\end{aligned}$$

Use a fórmula para normalizar o conjunto de dados `peixe` sem usar nenhum `for` ou `while`.

In [67]:
mi = np.mean(A, axis=0)
sigma = np.sqrt(1/(A.shape[0]-1)*np.sum((A-mi)**2,axis=0))

A = (A - mi)/sigma

print(A)
#o = np.sqrt((1/(n-1))*np.sum(A-mi))


# A = (A - u) / o

[[-0.87287156 -0.87287156]
 [-0.21821789  1.09108945]
 [ 1.09108945 -0.21821789]]


In [68]:
np.mean(A, axis=0)

array([0.00000000e+00, 2.77555756e-17])

In [138]:
# Escrever aqui

Média das colunas: [-7.56970244e-17  0.00000000e+00  1.16068771e-16]


### Encontrar raízes de funções

Dada uma função $f$, o seguinte procedimento consegue encontrar aproximar zeros desta função:

1. Inicialize $\tilde{x}_0$ com um chute inicial e escolha uma tolerância $\epsilon$;
2. Compute: $$\tilde{x}_{t} = \tilde{x}_{t-1} - \frac{f(\tilde{x}_{t-1})}{f'(\tilde{x}_{t-1})}$$
3. Repita o passo 2 até que $f(\tilde{x}_t) \leq \epsilon$.

Implemente esse procedimento para $f(x) = x^2 - 2$, teste seu resultado computando $\tilde{x} \cdot \tilde{x}$.

In [350]:
import random as rd

# Pegar um valor aleatório x0
x0 = rd.randrange(-60000, 60000)

#Tolerância e
e = 0.000001

#Adicionar o elemento x0 na matriz coluna de 100 linhas
X = np.vstack((x0, np.zeros((100, 1))))

# Definindo o X0, que é o inicial
f_x_current = ((x0**2) - 2)

i = 0

while f_x_current >= e and i<X.shape[0]-1:
    
    i += 1
    f_x_previous = ((X[i-1]**2) - 2)
    derivate_x_previous = (2*X[i-1])
    
    X[i] = X[i-1] - f_x_previous / derivate_x_previous
    
    f_x_current = ((X[i]**2)-2)

print("Stop iteration =", i)
print("Current X= ", X[i], "F(X)= ",f_x_current)
print("X' * X' = ", X[i]*X[i], "the expected value is 2")

Stop iteration = 18
Current X=  [-1.41421356] F(X)=  [1.44536161e-09]
X' * X' =  [2.] the expected value is 2


In [330]:
# for i in range(1, X.shape[0]):
    
#     x_current = X[i]
#     x_previous = X[i-1]
#     f_x_previous = (X[i-1]**2 - 2)
#     derivate_x_previous = (2*X[i-1])
    
#     x_current = x_previous - f_x_previous / derivate_x_previous


In [139]:
# Escrever aqui

### Resolver uma regressão linear através de mínimos quadrados ordinários

Como visto na aula de regressão linear, dado o seguinte problema:
$$\begin{aligned}
\boldsymbol{X}\boldsymbol{W}^{\mathbf{T}} = \hat{\boldsymbol{y}}\\
\text{Queremos encontrar:}\\
\tilde{\boldsymbol{W}} = \arg\min_{\boldsymbol{W}} ||\boldsymbol{W}^{\mathbf{T}} \boldsymbol{X} - \boldsymbol{y}||^2
\end{aligned}$$

Como visto, sabemos que:
$$\tilde{\boldsymbol{W}} = (\boldsymbol{X}^{\mathbf{T}}\boldsymbol{X})^{-1} \boldsymbol{X}^{\mathbf{T}}\boldsymbol{y}$$

Encontre o $\tilde{\boldsymbol{W}}$ pro dataset `peixe` onde:
$$\boldsymbol{X} = \mathtt{peixe\_dataset[:,[1,2]}\\\boldsymbol{y} = \mathtt{peixe\_dataset[:,[0]]}$$

Sem utilizar estrutura de repetição alguma, calcule a raíz do erro quadrático médio:
$$\mathrm{RMSE} = \sqrt{\frac{1}{n}\sum_i^n (\boldsymbol{y} - \hat{\boldsymbol{y}})^2}$$

In [137]:
# Escrever aqui

RMSE: 655.6771573167042
